# CI de nível 02 - Disparo agendado

name: 'Execução Agendada'

# regras de disparo (gatilhos/trigger)

on:
  schedule:
    - cron: '0 6 * * 1'

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    #máquina em que o job vai ser executado
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      #instalação do yarn
      - name: Instalando yarn
        run: npm install -g yarn

        #instalar dependencias com o Yarn
      - name: Instalando dependencias
        run: yarn

        #instalar browsers do playwright
      - name: Instalando playwright
        run: yarn playwright install

        # executar testes e2e
      - name: Executando Testes e2e
        run: yarn run e2e